### ISSUE TITLE
error pada dart versi 3.3.0

### ISSUE THREAD

**Issue by ryansyah17** [Farid023/flutter_tournament_bracket#1]
tidak support pada dart 3.3.0

**Comment by Farid023** [comment]
Hi, thank you for reporting this issue!

The problem was caused by the minimum Dart SDK version requirement in the package. I've updated the package to support Dart 3.3.0 and above. Please update to the latest version of the package (1.0.2) where this issue is resolved.

If you encounter any further issues, feel free to let me know.

Thanks for your feedback and support!

**Comment by farid023** [comment]
> tidak support pada dart 3.3.0

Hi, thank you for reporting this issue!

The problem was caused by the minimum Dart SDK version requirement in the package. I've updated the package to support Dart 3.0.0 and above. Please update to the latest version of the package (1.0.2) where this issue is resolved.

If you encounter any further issues, feel free to let me know.

Thanks for your feedback and support!
